"use strict";
const firstName = "Sunil";
const age = 29;
const male = true;
const numArr = [1, 2, 3, 4, 5];
const strArr = ["Sunil", "Kushal", "Rakesh", "Raju"];
const bolArr = [true, false, false, true];
console.log(firstName);
console.log(age);
console.log(male);
console.log(numArr);
console.log(numArr);
console.log(strArr);
console.log(bolArr);
